### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by yanwencaihubei** [Heeexy/SpringBoot-Shiro-Vue#54]
我将你的项目部署到idea后，前后端都可以启动，但是登录的时候后台报错了。

org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/json;charset=UTF-8' not supported
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:224)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:157)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:130)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:124)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:165)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)

**Comment by Heeexy** [comment]
org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'application/json;charset=UTF-8' not supported

有改动啥代码么

**Comment by yanwencaihubei** [comment]
没有改动啊，就部署启动，前后端启动，然后就打开了登录页面，然后就点击登录，就报错了

**Comment by yanwencaihubei** [comment]
vue启动和springboot启动都没有报错，登录页面也可以正常打开，但是就是点击登录后台报错了

**Comment by Heeexy** [comment]
单独请求localhost:8080的接口看看呢

**Comment by yanwencaihubei** [comment]
报了一样的错，这个是什么问题

**Comment by yanwencaihubei** [comment]
还有我的vue启动后默认打开的地址是这个
http://localhost:9520/#/login

**Comment by yanwencaihubei** [comment]
大神，我刚刚接触这个vue和springboot的整合，很多地方会很菜望大神带带我！

**Comment by Heeexy** [comment]
https://www.cnblogs.com/dbaxyx/p/6924459.html 
这个文章能解决么

**Comment by Heeexy** [comment]
> 还有我的vue启动后默认打开的地址是这个
> http://localhost:9520/#/login

前端启动用的是9520端口是对的

**Comment by yanwencaihubei** [comment]
对的，前端启动用的9520端口

**Comment by yanwencaihubei** [comment]
大神，谢谢！已经可以登录了。

**Comment by Heeexy** [comment]
> 大神，谢谢！已经可以登录了。

咋弄好的

**Comment by yanwencaihubei** [comment]
就是缺了包

<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.8.8.1</version>
</dependency>

引入包就OK了
